project_id = "wmbrnfocnlkhqflliaup"

[functions.auth-whoami]
verify_jwt = false

[functions.org-current]
verify_jwt = false

[functions.reports-sales-summary]
verify_jwt = false

[functions.audit-run]
verify_jwt = false

[functions.demo-protected]
verify_jwt = false

[functions.sales-totals]
verify_jwt = false

[functions.product-performance]
verify_jwt = false

[functions.daily-backup]
verify_jwt = false

[functions.machine-telemetry]
verify_jwt = false

[functions.machine-sales]
verify_jwt = false

[functions.machine-inventory-sync]
verify_jwt = false

[functions.machine-status]
verify_jwt = false