// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmbrnfocnlkhqflliaup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtYnJuZm9jbmxraHFmbGxpYXVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODIwNjEsImV4cCI6MjA3MzM1ODA2MX0.Wzt4HcA_I6xEV9CfvxrC4X97Z1dlUU4OGkX1t5m0rWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});